const ACTIONS = {
  USER_GETREQUEST: "USER_GETREQUEST",
  USER_GETREQUEST_SUCCESSFULL: "USER_GETREQUEST_SUCCESSFULL",
  USER_GETREQUEST_FAILURE: "USER_GETREQUEST_FAILURE",

  USER_POSTREQUEST: "USER_POSTREQUEST",
  USER_POSTREQUEST_SUCCESSFULL: "USER_POSTREQUEST_SUCCESSFULL",
  USER_POSTREQUEST_FAILURE: "USER_POSTREQUEST_FAILURE",

  USER_DELETEREQUEST: "USER_DELETEREQUEST",
  USER_DELETEREQUEST_SUCCESSFULL: "USER_DELETEREQUEST_SUCCESSFULL",
  USER_DELETEREQUEST_FAILURE: "USER_DELETEREQUEST_FAILURE",

  USER_EDITREQUEST: "USER_EDITREQUEST",
  USER_EDITREQUEST_SUCCESSFULL: "USER_EDITREQUEST_SUCCESSFULL",
  USER_EDITREQUEST_FAILURE: "USER_EDITREQUEST_FAILURE",
};

export default ACTIONS;
